<<<<<<< HEAD
title: Mariano POlitano # your name (or website title) here
logo: "/images/imPro.jpg
?raw=true" # your photo (or logo) here
=======
title: Mariano Politano # your name (or website title) here
logo: "/images/i1.jpg?raw=true" # your photo (or logo) here
>>>>>>> 9daead4a5daf864ddd71bf66475b1da5c49b68b9
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD student, Computer Science Department, University of Río Cuarto  <br><br>
  Argentina

  <br><br>
  <a href=www.linkedin.com/in/mpolitano">View My LinkedIn Profile</a> 

  <br><br>
  <a href=www.github.com/mpolitano">View My GitHub Profile</a> 
  
  <br><br>
  <a href="mailto:marianopolitano@dc.exa.unrc.edu.ar">Email Me</a> 

 
  <br><br>
  <a href="https://scholar.google.com/citations?user=E6lOziEAAAAJ&hl=es&oi=ao
"> Google Scholar</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
